# Generated by Django 4.2.2 on 2023-07-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_predict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predict',
            options={'verbose_name': 'Prediction', 'verbose_name_plural': 'Predictions'},
        ),
    ]
